config/routes.rb
Rails.application.routes.draw do
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins

  namespace :admin do
    resources :posts do
      collection do
        get :events
        get :approved
        get :rejected
        post :update_factor
        get :subscriptions
        get :status
        get :reminder_email
        get :download
      end

      member do
        get :approve
        get :reject
      end
    end
  end

  resources :accounts
  resources :posts do
    collection do
      get :approved
      get :pics
      post :tweet
      post :post_to_fb
      get :donation_raised
      post :subscribe
    end
  end
  get '/admin', to: 'admin/posts#dashboard'
  get '/home/inactive', to: 'home#inactive'
  root 'home#index'

end

app/models/post.rb
require 'csv'

class Post < ActiveRecord::Base
  def self.csv_file
    CSV.generate do |csv|
      csv << ["ID", "Username", "Content", "When?", "Provider", "Approved"]
      Post.all.each do |p|
        csv << [p.id, p.screen_name, p.content.to_s.gsub("\n", " "), p.created_at.strftime("%d-%m-%Y"), p.provider, p.approved]
      end
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def index
    @posts = Post.where("approved IS NULL")
  end

  def dashboard
  end

  def approved
    @posts = Post.where("approved = 1").paginate(:page => params[:page], :per_page => 25).order("created_at desc")
  end

  def rejected
    @posts = Post.where("approved = 0").paginate(:page => params[:page], :per_page => 25).order("created_at desc")
  end

  def events
    last_id = params[:last_id]
    posts = Post.where("id > #{last_id.to_i} AND approved IS NULL")
    respond_to do |format|
      format.json {render :json => {:posts => posts.to_json}}
    end
  end

  def approve
    post = Post.find_by_id params[:id]
    if post.present?
      post.update_attributes :approved => true, :approved_at => Time.now
    end
    respond_to do |format|
      format.json {render :json => {:success => true}.to_json}
    end
  end

  def reject
    post = Post.find_by_id params[:id]
    if post.present?
      post.update_attributes :approved => false
    end
    respond_to do |format|
      format.json {render :json => {:success => true}.to_json}
    end
  end

  def update_factor
    factor = DonationFactor.donation_per_post
    factor.update_attributes :factor => params[:factor].to_i
    respond_to do |format|
      format.json {render :json => {:success => true}.to_json}
    end
  end

  def subscriptions
    @subscriptions = Subscription.paginate(:per_page => 25, :page => params[:page])
  end

  def status
    AppStatus.current_status.update_attributes :running => params[:status]
    return redirect_to("/admin")
  end

  def reminder_email
    SubscriptionMailer.reminder_email.deliver
    return redirect_to("/admin")
  end

  def download
    respond_to do |format|
      format.csv {
        send_data Post.csv_file, :type => 'text/csv', :disposition => "attachment;filename=KaroMumkinPosts.csv"
      }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:tweet]
  def show
    post = Post.find_by_id params[:id]
    respond_to do |format|
      format.json {render :json => {:story => post.content}.to_json}
    end
  end

  def approved
    @page = params[:page].to_i
    offset = (@page - 1) * 8
    @posts = Post.where("approved = 1").offset(offset).limit(8).order("approved_at desc")
    render :layout => false
  end

  def pics
    @pics = Post.all.where("approved = 1").order("approved_at desc").collect{|post| [post.profile_pic, post.user_name]}.uniq
    render :layout => false
  end

  def donation_raised
    @posts_count = Post.where("approved = 1").count
    respond_to do |format|
      format.json {render :json => {:amount => @posts_count * DonationFactor.donation_per_post.factor}.to_json}
    end
  end

  def tweet
    if current_user.tweet(params[:tweet])
      unless params[:tweet].to_s =~ /#KaroMumkin/i
        Post.create :name => current_user.twitter_identity.user_name,
          :content     => params[:tweet],
          :user_name   => current_user.twitter_identity.user_name,
          :screen_name => current_user.twitter_identity.screen_name,
          :profile_pic => current_user.twitter_identity.profile_pic,
          :provider    => 'twitter'
      end
      respond_to do |format|
        format.json {render :json => {:success =>  true}.to_json}
      end
    else
      respond_to do |format|
        format.json {render :json => {:success => false}.to_json}
      end
    end
  end

  def post_to_fb
    if user_signed_in? and current_user.facebook_identity.present?
      graph = Koala::Facebook::API.new(current_user.facebook_identity.oauth_token)
      post = graph.get_object(params[:post_id])
      Post.create :name => post["from"]["name"],
        :content     => post["message"],
        :user_name   => post["from"]["name"],
        :screen_name => post["from"]["name"],
        :profile_pic => current_user.facebook_identity.profile_pic,
        :provider    => 'facebook'
      respond_to do |format|
        format.json {render :json => {:success =>  true}.to_json}
      end
    end
  end

  def subscribe
    success = false
    message = ""
    subscription = Subscription.find_by :email => params[:email]
    if subscription.present?
      message = "You have already subscribed. Please wait until the campaign starts"
    else
      Subscription.create :email => params[:email], :name => params[:name]
      success = true
      message = "You have subscribed successfully. We will notify you when the campaign starts."
    end
    respond_to do |format|
      format.json {render :json => {:success =>  success, :message => message}.to_json}
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/approved.html.erb
<div id="posts" style="padding-top: 80px;">
  <table class="table table-bordered posts-table">
    <% @posts.each do |post| %>
      <tr id="post-<%= post.id %>">
        <td><%= post.user_name %></td>
        <td><%= post.content %></td>
        <td><%= post.provider %></td>
      </tr>
    <% end %>
  </table>
</div>
<%= will_paginate @posts %>

app/views/admin/posts/dashboard.html.erb
<div style="padding-top: 50px;">
  <table style="width: 100%; text-align: center;" class="emails-table">
    <tbody>
      <tr>
        <td><h3>Donation per post</h3></td>
      </tr>
      <tr>
        <td>Rs. <input id="factor" name="factor" style="width: 60px;" value="<%= DonationFactor.donation_per_post.factor %>" /></td>
      </tr>
      <tr>
        <td><a href="#" id="update-factor">Update</a></td>
      </tr>
    </tbody>
  </table>
</div>

<div style="padding-top: 50px;">
  <div class="row">
    <div class="col-xs-5"></div>
    <div class="col-xs-2">App is currently <strong><%= AppStatus.current_status.running.upcase %></strong></div>
    <div class="col-xs-5"></div>
  </div>
  <div class="row">
    <% if AppStatus.current_status.running == "paused" %>
      <div class="col-xs-5"></div>
      <div class="col-xs-1"><a href="/admin/posts/status?status=active">Activate</a></div>
      <div class="col-xs-1"><a href="/admin/posts/status?status=inactive">Inactivate</a></div>
      <div class="col-xs-5"></div>
    <% elsif AppStatus.current_status.running == "active" %>
      <div class="col-xs-5"></div>
      <div class="col-xs-1"><a href="/admin/posts/status?status=paused">Pause</a></div>
      <div class="col-xs-1"><a href="/admin/posts/status?status=inactive">Inactivate</a></div>
      <div class="col-xs-5"></div>
    <% else %>
      <div class="col-xs-5"></div>
      <div class="col-xs-2"><a href="/admin/posts/status?status=active">Activate</a></div>
      <div class="col-xs-5"></div>
    <% end %>
  </div>
</div>

<div style="padding-top: 50px;">
  <div class="row">
    <div class="col-xs-5"></div>
    <div class="col-xs-2"><strong><a href="/admin/posts/reminder_email">Send reminder e-mail</a></strong></div>
    <div class="col-xs-5"></div>
  </div>
</div>

<div style="padding-top: 50px;">
  <div class="row">
    <div class="col-xs-5"></div>
    <div class="col-xs-2"><strong><a href="<%= download_admin_posts_path :format => 'csv' %>">Download Posts</a></strong></div>
    <div class="col-xs-5"></div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<% content_for :head do %>
  <script>
    var last_id = null;
  </script>
<% end %>
<div id="posts" style="padding-top: 80px;">
  <table class="table table-bordered posts-table">
    <% @posts.each do |post| %>
      <tr id="post-<%= post.id %>">
        <td><%= post.user_name %></td>
        <td><%= post.content %></td>
        <td><a href="#" class="approve-post" data-id="<%= post.id %>">Approve</a></td>
        <td><a href="#" class="reject-post" data-id="<%= post.id %>">Reject</a></td>
        <td><%= post.provider %></td>
      </tr>
      <script>last_id = <%= post.id %>;</script>
    <% end %>
  </table>
</div>

app/views/admin/posts/rejected.html.erb
<div id="posts" style="padding-top: 80px;">
  <table class="table table-bordered posts-table">
    <% @posts.each do |post| %>
      <tr id="post-<%= post.id %>">
        <td><%= post.user_name %></td>
        <td><%= post.content %></td>
        <td><%= post.provider %></td>
      </tr>
    <% end %>
  </table>
</div>
<%= will_paginate @posts %>

app/views/admin/posts/subscriptions.html.erb
<div id="subscriptions" style="padding-top: 80px;">
  <table class="table table-bordered posts-table">
    <% @subscriptions.each do |s| %>
      <tr>
        <td><%= s.name %></td>
        <td><%= s.email %></td>
      </tr>
    <% end %>
  </table>
</div>
<%= will_paginate @subscriptions %>